In [3]:
# import the necessary packages
import numpy as np
import cv2

boundingBoxes = np.array([
	(12, 84, 140, 212, 0.3),
	(24, 84, 152, 212, 0.4),
	(36, 84, 164, 212, 0.5),
	(12, 96, 140, 224, 0.6),
	(24, 96, 152, 224, 0.7),
	(24, 108, 152, 236, 0.8)])

# load the image and clone it
image = cv2.imread("cat_nms.png")
orig = image.copy()
# loop over the bounding boxes for each image and draw them
for (startX, startY, endX, endY, confidence) in boundingBoxes:
	cv2.rectangle(orig, (int(startX), int(startY)), (int(endX), int(endY)), (0, 0, 255), 2)
# # perform non-maximum suppression on the bounding boxes
pick = non_max_suppression(boundingBoxes, 0.3)
# # loop over the picked bounding boxes and draw them
# for (startX, startY, endX, endY, confidence) in pick:
#    print(startX,startY,endX,endY)
#    cv2.rectangle(image, (startX, startY), (endX, endY), (0, 255, 0), 2)
# display the images
# cv2.imshow('orig',orig)
# cv2.imshow(image)
# cv2.waitKey()
cv2.imwrite('out.png',orig)


[12. 24. 36. 12. 24. 24.]
[ 84.  84.  84.  96.  96. 108.]
[140. 152. 164. 140. 152. 152.]


True

In [19]:
def non_max_suppression(boxes, overlapThresh):
    # if there are no boxes, return an empty list
    if len(boxes) == 0:
        return []
    # initialize the list of picked indexes	
    pick = []
    x1 = boxes[:, 0]
    print(f"==>> x1: {x1}")
    y1 = boxes[:, 1]
    x2 = boxes[:, 2]
    y2 = boxes[:, 3]
    c = boxes[:, 4]
    # compute the area of intersection rectangle
    area = (x2 - x1 + 1) * (y2 - y1 + 1)
    idxs = np.argsort(c)
    print(f"==>> idxs: {idxs}")
    while len(idxs) > 0:
        # grab the last index in the indexes list and add the
        # index value to the list of picked indexes
        last = len(idxs) - 1
        i = idxs[last]
        pick.append(i)
        # find the largest (x, y) coordinates for the start of
        # the bounding box and the smallest (x, y) coordinates
        # for the end of the bounding box
        xx1 = np.maximum(x1[i], x1[idxs[:last]])
        print(f"==>> idxs[:last]: {idxs[:last]}")
        yy1 = np.maximum(y1[i], y1[idxs[:last]])
        xx2 = np.minimum(x2[i], x2[idxs[:last]])
        yy2 = np.minimum(y2[i], y2[idxs[:last]])
        print(f"==>> x1[idxs[:last]]: {x1[idxs[:last]]}")
        print(f"==>> x1[i]: {x1[i]}")
        # compute the width and height of the bounding box
        w = np.maximum(0, xx2 - xx1 + 1)
        h = np.maximum(0, yy2 - yy1 + 1)
        # compute the ratio of overlap
        overlap = (w * h) / area[idxs[:last]]
        print(f"==>> overlap: {overlap}")
        idxs = np.delete(idxs, np.concatenate(([last],
                                               np.where(overlap > overlapThresh)[0])))
        print(f"==>> idxs: {idxs}")
    return boxes[pick].astype("int")
        # break


# import the necessary packages
import numpy as np
import cv2

boundingBoxes = np.array([
	(12, 84, 140, 212, 0.3),
	(24, 84, 152, 212, 0.4),
	(36, 84, 164, 212, 0.5),
	(12, 96, 140, 224, 0.6),
	(24, 96, 152, 224, 0.7),
	(24, 108, 152, 236, 0.8)])

# load the image and clone it
image = cv2.imread("cat_nms.png")
orig = image.copy()
# loop over the bounding boxes for each image and draw them
for (startX, startY, endX, endY, confidence) in boundingBoxes:
	cv2.rectangle(orig, (int(startX), int(startY)), (int(endX), int(endY)), (0, 0, 255), 2)
# # perform non-maximum suppression on the bounding boxes
pick = non_max_suppression(boundingBoxes, 0.8)
# # loop over the picked bounding boxes and draw them
for (startX, startY, endX, endY, confidence) in pick:
   print(startX,startY,endX,endY)
   cv2.rectangle(image, (startX, startY), (endX, endY), (0, 255, 0), 2)
# display the images
# cv2.imshow('orig',orig)
# cv2.imshow(image)
# cv2.waitKey()
cv2.imwrite('orig.png',orig)
cv2.imwrite('image.png',image)




==>> x1: [12. 24. 36. 12. 24. 24.]
==>> idxs: [0 1 2 3 4 5]
==>> idxs[:last]: [0 1 2 3 4]
==>> x1[idxs[:last]]: [12. 24. 36. 12. 24.]
==>> x1[i]: 24.0
==>> overlap: [0.73823688 0.81395349 0.73823688 0.82260681 0.90697674]
==>> idxs: [0 2]
==>> idxs[:last]: [0]
==>> x1[idxs[:last]]: [12.]
==>> x1[i]: 36.0
==>> overlap: [0.81395349]
==>> idxs: []
24 108 152 236
36 84 164 212


True